(* ::Package:: *)

PacletObject[<|
  "Name" -> "WolframInstitute/WAnim",
  "PublisherID" -> "WolframInstitute",
  "Version" -> "1.0.2",
  "WolframVersion" -> "15.0+",
  "Description" -> "Live audiovisual coding: Manim-style scenes, films and Strudel-style music as graphics and patterns in time",
  "Creator" -> "Nikolay Murzin, Claude (Anthropic)",
  "License" -> "MIT",
  "Keywords" -> {"animation", "live coding", "music", "Strudel", "TidalCycles", "patterns", "audio", "video", "timeline", "motion graphics"},
  "Categories" -> {"Graphics & Visualization", "Music"},
  "PrimaryContext" -> "WolframInstitute`WAnim`",
  "Dependencies" -> {"Wolfram/Parser" -> ">=1.1"},
  "Extensions" -> {
    {"LibraryLink", "Root" -> "LibraryResources"},
    {
      "Kernel",
      "Root" -> "Kernel",
      "Context" -> {"WolframInstitute`WAnim`", {"WolframInstitute`WAnim`Strudel`", "Strudel.wl"}},
      "Symbols" -> {
        "WolframInstitute`WAnim`AnimatedGraphics",
        "WolframInstitute`WAnim`AnimationEffect",
        "WolframInstitute`WAnim`ArchiveClip",
        "WolframInstitute`WAnim`AutomatonTape",
        "WolframInstitute`WAnim`Backdrop",
        "WolframInstitute`WAnim`BraceLabel",
        "WolframInstitute`WAnim`CanvasClip",
        "WolframInstitute`WAnim`CanvasDisk",
        "WolframInstitute`WAnim`CanvasFont",
        "WolframInstitute`WAnim`CanvasGradient",
        "WolframInstitute`WAnim`CanvasImage",
        "WolframInstitute`WAnim`CanvasLine",
        "WolframInstitute`WAnim`CanvasOpacity",
        "WolframInstitute`WAnim`CanvasPolygon",
        "WolframInstitute`WAnim`CanvasRectangle",
        "WolframInstitute`WAnim`CanvasRotate",
        "WolframInstitute`WAnim`CanvasScale",
        "WolframInstitute`WAnim`CanvasScreen",
        "WolframInstitute`WAnim`CanvasText",
        "WolframInstitute`WAnim`CanvasTextWidth",
        "WolframInstitute`WAnim`CanvasTransform",
        "WolframInstitute`WAnim`CanvasTranslate",
        "WolframInstitute`WAnim`CanvasWrap",
        "WolframInstitute`WAnim`CaptionText",
        "WolframInstitute`WAnim`DictionaryCard",
        "WolframInstitute`WAnim`Easing",
        "WolframInstitute`WAnim`GPUGraphics",
        "WolframInstitute`WAnim`Instrument",
        "WolframInstitute`WAnim`Mixer",
        "WolframInstitute`WAnim`Morph",
        "WolframInstitute`WAnim`NotebookEra",
        "WolframInstitute`WAnim`NotebookSession",
        "WolframInstitute`WAnim`NumberCounter",
        "WolframInstitute`WAnim`OrderedDither",
        "WolframInstitute`WAnim`PartialPath",
        "WolframInstitute`WAnim`PhotoPrint",
        "WolframInstitute`WAnim`Spikey",
        "WolframInstitute`WAnim`TerminalSession",
        "WolframInstitute`WAnim`TileGrid",
        "WolframInstitute`WAnim`TitleCard",
        "WolframInstitute`WAnim`Track",
        "WolframInstitute`WAnim`TrackAlternate",
        "WolframInstitute`WAnim`TrackDegrade",
        "WolframInstitute`WAnim`TrackEuclid",
        "WolframInstitute`WAnim`TrackEvery",
        "WolframInstitute`WAnim`TrackPause",
        "WolframInstitute`WAnim`TrackPlay",
        "WolframInstitute`WAnim`TrackPulse",
        "WolframInstitute`WAnim`TrackScale",
        "WolframInstitute`WAnim`TrackSeek",
        "WolframInstitute`WAnim`TrackSequence",
        "WolframInstitute`WAnim`TrackShift",
        "WolframInstitute`WAnim`TrackSpeed",
        "WolframInstitute`WAnim`TrackStruct",
        "WolframInstitute`WAnim`TrackSuperimpose",
        "WolframInstitute`WAnim`TrackView",
        "WolframInstitute`WAnim`TreeDiagram",
        "WolframInstitute`WAnim`Tween",
        "WolframInstitute`WAnim`TypedText",
        "WolframInstitute`WAnim`Typewriter",
        "WolframInstitute`WAnim`WordScroll",
        "WolframInstitute`WAnim`WordWall",
        "WolframInstitute`WAnim`YearRuler",
        "WolframInstitute`WAnim`$AudioLatency",
        "WolframInstitute`WAnim`$CyclesPerSecond",
        "WolframInstitute`WAnim`Strudel`a",
        "WolframInstitute`WAnim`Strudel`beat",
        "WolframInstitute`WAnim`Strudel`cat",
        "WolframInstitute`WAnim`Strudel`d",
        "WolframInstitute`WAnim`Strudel`dec",
        "WolframInstitute`WAnim`Strudel`degrade",
        "WolframInstitute`WAnim`Strudel`dly",
        "WolframInstitute`WAnim`Strudel`early",
        "WolframInstitute`WAnim`Strudel`euclid",
        "WolframInstitute`WAnim`Strudel`every",
        "WolframInstitute`WAnim`Strudel`f",
        "WolframInstitute`WAnim`Strudel`fast",
        "WolframInstitute`WAnim`Strudel`g",
        "WolframInstitute`WAnim`Strudel`gain",
        "WolframInstitute`WAnim`Strudel`instrument",
        "WolframInstitute`WAnim`Strudel`late",
        "WolframInstitute`WAnim`Strudel`n",
        "WolframInstitute`WAnim`Strudel`name",
        "WolframInstitute`WAnim`Strudel`note",
        "WolframInstitute`WAnim`Strudel`off",
        "WolframInstitute`WAnim`Strudel`p",
        "WolframInstitute`WAnim`Strudel`pan",
        "WolframInstitute`WAnim`Strudel`ps",
        "WolframInstitute`WAnim`Strudel`punchcard",
        "WolframInstitute`WAnim`Strudel`r",
        "WolframInstitute`WAnim`Strudel`rev",
        "WolframInstitute`WAnim`Strudel`room",
        "WolframInstitute`WAnim`Strudel`s",
        "WolframInstitute`WAnim`Strudel`sc",
        "WolframInstitute`WAnim`Strudel`scale",
        "WolframInstitute`WAnim`Strudel`seq",
        "WolframInstitute`WAnim`Strudel`silence",
        "WolframInstitute`WAnim`Strudel`slow",
        "WolframInstitute`WAnim`Strudel`sound",
        "WolframInstitute`WAnim`Strudel`stack",
        "WolframInstitute`WAnim`Strudel`struct",
        "WolframInstitute`WAnim`Strudel`superimpose",
        "WolframInstitute`WAnim`Strudel`t",
        "WolframInstitute`WAnim`Strudel`x"
      }
    },
    {
      "Documentation",
      "Root" -> "Documentation",
      "Language" -> "English"
    },
    {
      "Test",
      "Root" -> "Tests",
      "Method" -> "Experimental-v1"
    },
    {
      "Asset",
      "Root" -> "Assets",
      "Assets" -> {
        {"Drums", "Drums"},
        {"Spikeys", "Spikeys"},
        {"Hero", "hero.png"}
      }
    }
  }
|>]
