(* Tests for the timeline, canvas kit and creation tools.  Run: TestReport["WAnim/Tests/Toolkit.wlt"] after loading the paclet. *)

VerificationTest[Head[Typewriter["abc", {0, 1}]], TimelineLayer, TestID -> "Typewriter-returns-layer"]
VerificationTest[Typewriter["abc", {0, 1}]["Span"], {0, 1}, TestID -> "Typewriter-span"]
VerificationTest[Caption["a b", {0, 1}]["Span"], {0, 1.25}, TestID -> "Caption-span-includes-exit"]
VerificationTest[Caption["a b", {0, 1}]["Shift", 2]["Span"], {2, 3.25}, TestID -> "Layer-shift"]
VerificationTest[Timeline[{Red, Title["x", {0, 3}]}]["Duration"], 3, TestID -> "Timeline-duration-from-layers"]
VerificationTest[Timeline[{Red}, "Duration" -> 16, "SecondsPerUnit" -> 2]["Seconds"], 32, TestID -> "Timeline-seconds"]
VerificationTest[ImageDimensions[Timeline[{Blue}, "Duration" -> 1, "Size" -> {320, 180}]["Image", 0.5]], {320, 180}, TestID -> "Timeline-image-size"]
VerificationTest[Head[Timeline[{Blue}, "Duration" -> 1]["Graphics", 0.5]], Graphics, TestID -> "Timeline-graphics"]
VerificationTest[Easing["OutCubic"][0.5], 0.875, TestID -> "Easing-outcubic"]
VerificationTest[Easing["Linear"] /@ {-1, 0.3, 2}, {0, 0.3, 1}, TestID -> "Easing-clamps"]
VerificationTest[TypedText["hello", 0.4], "he", TestID -> "TypedText"]
VerificationTest[CanvasTextWidth["abc", CanvasFont["Source Code Pro", 10]] > 0, True, TestID -> "CanvasTextWidth-positive"]
VerificationTest[Length[CanvasWrap["aaa bbb ccc ddd", CanvasFont["Source Code Pro", 10], 40]] > 1, True, TestID -> "CanvasWrap-wraps"]
VerificationTest[Sort[Keys[$DrumKit]], {"bd", "cp", "cr", "hh", "lt", "oh", "rim", "sd"}, TestID -> "DrumKit-names"]
VerificationTest[Length[EventTrack[{{0, 1/2, 60}, {1/2, 1/2, 64}, {1, 1, 67}}]["Query", 0, 1]], 2, TestID -> "EventTrack-query"]
VerificationTest[TrackPulse[EventTrack[{{0, 1/4, "bd"}}], 18][0], 1., TestID -> "TrackPulse-onset"]
VerificationTest[Track["bd sd, hh*4"]["Query", 0, 1][[All, "Value"]], {"bd", "sd", "hh", "hh", "hh", "hh"}, TestID -> "Track-top-level-stack"]
VerificationTest[Track["bd [sd"], Silence, {Track::parse}, TestID -> "Track-parse-message"]
VerificationTest[Block[{$CyclesPerSecond = 1/2}, Max[Abs[AudioData[Audio[Track["bd sd, hh*4"], 1]]]] > 0.5], True, TestID -> "Track-stack-sounds"]
VerificationTest[Length[NotebookEra[]], 10, TestID -> "NotebookEra-names"]
VerificationTest[NotebookEra["BigSur2020", "Page" -> Black]["Page"], Black, TestID -> "NotebookEra-change"]
VerificationTest[AllTrue[NotebookEra[], FreeQ[NotebookSession[{{0, "In", "1 + 1"}}, {0, 1}, "Era" -> #, "Evaluate" -> True]["Graphics", 0.9], _Missing | $Failed] &], True, TestID -> "NotebookEra-all-draw"]
VerificationTest[Round[QuantityMagnitude[Duration[Timeline[{Backdrop[Black]}, "Duration" -> 1, "SecondsPerUnit" -> 2, "Soundtrack" -> Track["bd*4"]]["Audio"]], "Seconds"], 0.01], 2., TestID -> "Timeline-tempo-from-SecondsPerUnit"]
VerificationTest[Head[NotebookSession[{{0, "In", "1 + 1"}}, {0, 1}, "Evaluate" -> True]["Graphics", 0.9]], Graphics, TestID -> "NotebookSession-evaluates"]
VerificationTest[Head[Spikey[{0, 1}, "Form" -> "Hexecontahedron"]["Graphics", 0.5]], Graphics, TestID -> "Spikey-form"]
VerificationTest[Head[TreeDiagram[Hold[{x -> 1, f[y]}], {0, 2}]["Graphics", 1.5]], Graphics, TestID -> "TreeDiagram-draws"]
VerificationTest[Head[TileGrid[{{"Plot", Plot[x, {x, 0, 1}], "1.0"}}, {0, 2}]["Graphics", 1]], Graphics, TestID -> "TileGrid-draws"]
VerificationTest[Head[WordScroll[{"Plot", "ListPlot"}, {0, 2}]["Graphics", 1]], Graphics, TestID -> "WordScroll-draws"]
VerificationTest[FreeQ[Title["Wolfram Language", {0, 2}, "Highlight" -> "Wolfram"]["Graphics", 1], RGBColor["#DD1100"]], False, TestID -> "Title-highlight"]
VerificationTest[FreeQ[Title["ink", {0, 2}, FontColor -> (If[# < 1, Red, Blue] &)]["Graphics", 1.5], Blue], False, TestID -> "Colour-as-function-of-time"]
VerificationTest[Round[QuantityMagnitude[Duration[Audio[Track["bd*4"], 2, "CyclesPerSecond" -> 1/2]], "Seconds"], 0.01], 4., TestID -> "Audio-tempo-option"]
VerificationTest[Round[QuantityMagnitude[Duration[Audio[Synth["Riser"][EventTrack[{{0, 2, 60}}]], 2, "CyclesPerSecond" -> 1/2]], "Seconds"], 0.01], 4., TestID -> "Synth-shaped-timbre"]
VerificationTest[FreeQ[NotebookSession[{{0, "In", "1"}}, {0, 4}, "Hide" -> {{1, 2}}]["Graphics", 1.5], _Inset], True, TestID -> "NotebookSession-hide"]
VerificationTest[Tween[{0, 1}] /@ {-1, 0.5, 2}, {0, 0.5, 1}, SameTest -> (Norm[N[#1 - #2]] < 10^-6 &), TestID -> "Tween-clamped"]
VerificationTest[Tween[{{1, 110}, {2, 40}, {3, 180}}] /@ {0, 2, 5}, {110, 40, 180}, TestID -> "Tween-keyframes"]
VerificationTest[Length[First[Morph[Rectangle[{-1, -1}, {1, 1}], Disk[]][0.5]]], 120, TestID -> "Morph-points"]
VerificationTest[Round[Total[Norm /@ Differences[First[PartialPath[Circle[], 1/2]]]], 0.01], Round[N[Pi], 0.01], TestID -> "PartialPath-half-circle"]
VerificationTest[Length[AnimatedObject[{"a", "+", "b"}]["Primitives"]], 3, TestID -> "AnimatedObject-tex-parts"]
VerificationTest[Head[Timeline[{Stage[{AnimatedObject[Disk[]]["Play", "Transform", AnimatedObject[Rectangle[]]]}, {0, 1}]}, "Duration" -> 1]["Graphics", 0.5]], Graphics, TestID -> "Stage-plays-objects"]
VerificationTest[Head[Timeline[{Stage[Function[t, {White, Disk[{t, 0}, 0.5], Text["hi", {0, 2}]}], {0, 1}]}, "Duration" -> 1, Background -> Black]["Graphics", 0.5]], Graphics, TestID -> "Stage-draws"]
VerificationTest[Head[Timeline[{Backdrop[Red]}, "Duration" -> 0.2, "Size" -> {160, 90}]["AnimatedImage", "FrameRate" -> 10]], AnimatedImage, TestID -> "Timeline-AnimatedImage"]
VerificationTest[Length[Instrument[]], 20, TestID -> "Instrument-list"]
VerificationTest[With[{a = Audio[Mixer["Sidechain" -> EventTrack[{{0, 1/4, "bd"}}]][Track[{Instrument["Kick"][EventTrack[{{0, 1/4, "bd"}}]], Instrument["Pluck"][EventTrack[{{1/2, 1/8, 69, 0.8}}]]}]], 1, "CyclesPerSecond" -> 1/2]},
    {AudioChannels[a], Round[QuantityMagnitude[Duration[a], "Seconds"], 0.01], AudioMeasurements[a, "Max"] > 0.1}], {2, 2., True}, TestID -> "Instrument-mix"]
VerificationTest[Length[Cases[First[Timeline[{Typewriter["abc", {0, 1}, "TypingTime" -> 0.5]}, "Duration" -> 1, "Foley" -> True]]["FoleyEvents"], {_, "Tick", _}]], 3, TestID -> "Timeline-foley"]
VerificationTest[With[{w = WordWall[{{"alpha", 1., 0}, {"beta", 0.1, 0}}, {0, 1}]}, {Sort[Keys[w["Places"]]], Head[Timeline[{WordWall[{{"alpha", 1., 0}, {"beta", 0.1, 0}}, {0, 1},
    "Camera" -> (CanvasScale[3, w["Places"]["alpha"]] &), "Emphasis" -> ({# === "beta" &, 1} &)]}, "Duration" -> 1]["Graphics", 0.5]]}], {{"alpha", "beta"}, Graphics}, TestID -> "WordWall-camera"]
VerificationTest[Head[Timeline[{Spikey[{0, 1}, "Face" -> True, "Raise" -> (# &), "Blink" -> (# > 0.5 &), Position -> ({100 + 50 #, 100} &)]}, "Duration" -> 1]["Graphics", 0.7]], Graphics, TestID -> "Spikey-face"]
VerificationTest[Length[Cases[First[Timeline[{NotebookSession[{{0, "ChatInput", "hello", 0.3}, {0.5, "ChatOutput", "hi", {"1 + 1"}}}, {0, 1}, "Era" -> "BigSur2020",
    "ChatBar" -> {0.6, "ok", 0.1, 0.8}]}, "Duration" -> 1, "Foley" -> True]]["FoleyEvents"], {_, "Tick", _}]], 9, TestID -> "NotebookSession-chat-foley"]
